# disable autofixing PRs, commenting "pre-commit.ci autofix" on a pull request triggers a autofix
ci:
  autofix_prs: false
# generally speaking we ignore all vendored code as well as tests data
# ignore patches/diffs since slight reformatting can break them
exclude: |
  (?x)^(
    conda/_vendor |
    conda/auxlib |
    tests/data/(
      conda_format_repo |
      env_metadata/.+ |
      legacy_repodata |
      repodata |
      tar_traversal |
      corrupt
    ) |
    .*\.(patch|diff) |
    tools/vendoring/patches
  )/
repos:
  # generic verification and formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # standard end of line/end of file cleanup
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # ensure syntaxes are valid
      - id: check-toml
      - id: check-yaml
        exclude: ^(conda\.)?recipe/meta.yaml
      # catch git merge/rebase problems
      - id: check-merge-conflict
      # sort requirements files
      - id: file-contents-sorter
        files: ^tests/requirements.*\.txt
        args: [--unique]
  # Python verification and formatting
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      # auto inject license blurb
      - id: insert-license
        files: \.py$
        exclude: |
          (?x)^(
            conda/gateways/connection/adapters/ftp.py |  # Apache 2.0
            conda/gateways/disk/link.py  # MIT
          )$
        args: [--license-filepath, .github/disclaimer.txt, --no-extra-eol]
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      # auto format Python codes within docstrings
      - id: blacken-docs
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      # lint & attempt to correct failures (e.g. pyupgrade)
      - id: ruff
        args: [--fix]
      # compatible replacement for black
      - id: ruff-format
  - repo: meta
    # see https://pre-commit.com/#meta-hooks
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: git-diff
        name: git diff
        entry: git diff --exit-code
        language: system
        pass_filenames: false
        always_run: true
